### ISSUE TITLE
Create README for CLI version

### ISSUE THREAD

**Issue by kaitoii11** [Medha-B/XitoSBML#9]
create a README to guide the user how to run the cli version. 

README is probably best to create in `src/main/java/jp/ac/keio/bio/fun/xitosbml/cli/`

**Comment by Medha-B** [comment]
I am at an impasse with this issue right now because the mvn package is not working right on my environment. But since the code compiles correctly, should I at least start writing the README.md? I could look for fixing the mvn package problem along the way...

**Comment by kaitoii11** [comment]
Yes, you should start writing it in a different branch.

**Comment by Medha-B** [comment]
Please refer to https://github.com/Medha-B/XitoSBML/pull/20 for this issue.

Note:
1. I will add the part regarding the option for domain structure once you approve https://github.com/Medha-B/XitoSBML/pull/18
2. While writing about the usage of CliRun for the image folder, I noticed that we do not actually need any argument for the output since we save it in the same directory and only change the suffix of the input images. 
https://github.com/Medha-B/XitoSBML/blob/2b1c5b85c210ba3538ba19f90380913cbce81d14/src/main/java/jp/ac/keio/bio/fun/xitosbml/cli/CliRun.java#L62
Do you think it would be better to allow the users to choose a suffix for the output SBML models using the -o argument?

Please let me know what you think of this.

**Comment by kaitoii11** [comment]
> Do you think it would be better to allow the users to choose a suffix for the output SBML models using the -o argument?

This sounds like a good idea!

**Comment by Medha-B** [comment]
Thanks! Will make the changes soon.
